site_name: My Docs

site_url: https://shyokote.github.io/

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  font:
    text: Noto Sans JP
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate

nav:
  - HOME: index.md
  - Git:
    - Delete the entire contents of a Git repository: _git/delete_contents_git_repository.md
  - Linux:
    - Removing unnecessary Linux kernels: _linux/delete_linux_kernel.md
    - Virtualization changes in RockyLinux10 (RHEL10): _linux/virtualization_changes_in_rhel10.md
    - LVM extension extension on Linux: _linux/linux_extension_extension_on_Linux.md
    - Add disk on Linux: _linux/add_disk_on_Linux.md
    - Locking a package version: _linux/linux_package_versionlock.md
    - SSH authentication key public key remote distribution: _linux/remotely_distribute_ssh_keys.md
    - Recovering a public key from an SSH private key: _linux/recovering_public_key.md
    - Identify programs that expose files: _linux/lsof.md
    - Zabbix server cannot be stopped or shut down: _linux/zabbixserver_cannot_shutdown.md
    - How to fix Ubuntu dpkg lock error: _linux/ubuntu_dpkg_lock_error.md
  - Windows:
    - Apps won't disappear from the Windows Start menu: _windows/apps_wont_diappear_form_the_windows_menu.md
    - Unable to remove Linux installed with WSL: _windows/remove_linux_installed_with_wsl.md
  - Mac:
    - Create a Bootable USB from an ISO image using Mac's standard functions: _mac/create_bootableusb_mac.md
    - Create a Password-Secured Zip: _mac/create_password_secured_zip.md
  - Network:
    - YAMAHA:
      - YAMAHA RTX1210 initial setting example: _network/yamaha_rtx1210_init_settings.md
#    - Cisco:
  - Blog:
      - _blog/index.md

plugins:
  - search:
      lang: 'ja'
  - glightbox
  - blog:
      blog_dir: _blog
      blog_toc: true
      post_dir: "{blog}/articles"
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_url_max_categories: 10

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.keys

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css
  - _css/styles.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js

use_directory_urls: false
